config/routes.rb
Rails.application.routes.draw do

  # get 'customers/alphabetized'
  # get 'customers/missing_email', to: 'customers#missing_email', as: 'missing_email_customers'
  resources :customers do
    collection do
      get 'alphabetized'
      get 'missing_email'
    end
  end

  root to: 'customers#index'

  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/admin_user.rb
class AdminUser < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, 
         :recoverable, :rememberable, :trackable, :validatable
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/customer.rb
class Customer < ApplicationRecord
  belongs_to :province

  validates :name, presence: true
end

app/models/province.rb
class Province < ApplicationRecord
  has_many :customers

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/customers_controller.rb
class CustomersController < ApplicationController
  def index
    @customers = Customer.all
  end

  def alphabetized
    @customers = Customer.order(:name)
  end

  def missing_email
    @customers = Customer.where(email: [nil, ''])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/customers_helper.rb
module CustomersHelper
end

app/views/common/_header.html.erb
<header>
  <nav>
    <ul>
      <li>
        <%= link_to 'All', root_path %>
      </li>
      <li>
        <%= link_to 'By Name', alphabetized_customers_path %>
      </li>
      <li>
        <%= link_to 'Missing email', missing_email_customers_path %>
      </li>
    </ul>
  </nav>
</header>

app/views/customers/_customer.html.erb
<div class="customer_box">

  <h3>
    <%= customer.name %>
  </h3>

  <p>
    <%= image_tag customer.image %>
  </p>

  <p>
    <b>Province: </b>
    
    <% if customer.province.nil? %>
      None
    <% else %>
      <%= customer.province.name %>
    <% end %>
  </p>

  <p>
    <%= customer.phone %>
  </p>

  <p>
    <%= customer.email %>
  </p>

</div>

app/views/customers/alphabetized.html.erb
<h1>All Customers ordered by name</h1>

<%= render partial: 'customer',
           collection: @customers %>

app/views/customers/index.html.erb
<h1>All Customers</h1>

<%= render partial: 'customer',
           collection: @customers %>

app/views/customers/missing_email.html.erb
<h1>All Customers with missing email</h1>

<%= render partial: 'customer',
           collection: @customers %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>U6Crm</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= render partial: 'common/header' %>
    <%= yield %>
  </body>
</html>